version: '2.3'

services:
  mapserver:
    image: camptocamp/mapserver:8.0
    user: www-data
    entrypoint: []
    environment:
      - MAPSERVER_CONFIG_FILE=/etc/mapserver/mapserver.conf
    volumes:
      - ./mapserver:/etc/mapserver
    ports:
      - 8081:8080

  mapserver-fix:
    image: sitn/mapserver
    user: www-data
    entrypoint: []
    environment:
      - MAPSERVER_CONFIG_FILE=/etc/mapserver/mapserver.conf
    volumes:
      - ./mapserver:/etc/mapserver
    ports:
      - 8082:8080